# docker-compose.yml

services:
  telegram-bot-1:
    build: .
    container_name: coinbeats-telegram-bot-1
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MEDIA_PATH: ${MEDIA_PATH}
      ADMIN_USERS: ${ADMIN_USERS}
      DATABASE_URL: ${DATABASE_URL}
    # Instead of "expose:", use "ports:" to publish 8443 on the host
    ports:
      - "${PORT}:${PORT}"
    restart: always

  telegram-bot-2:
    build: .
    container_name: coinbeats-telegram-bot-2
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MEDIA_PATH: ${MEDIA_PATH}
      ADMIN_USERS: ${ADMIN_USERS}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    restart: always

  telegram-bot-3:
    build: .
    container_name: coinbeats-telegram-bot-3
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      MEDIA_PATH: ${MEDIA_PATH}
      ADMIN_USERS: ${ADMIN_USERS}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${PORT}:${PORT}"
    restart: always
