"""Add first_start_param to User

Revision ID: 07c8ba478f3d
Revises: 3bcc9d1d5b1b
Create Date: 2024-12-23 20:42:02.381952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c8ba478f3d'
down_revision = '3bcc9d1d5b1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_start_param', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_start_param')
    # ### end Alembic commands ###
