"""Create users table

Revision ID: f21b3f75c773
Revises: 4990269be2db
Create Date: 2025-01-03 09:43:48.350362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21b3f75c773'
down_revision = '4990269be2db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
